# Generated by Django 3.2.10 on 2023-04-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='url',
        ),
    ]
